services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: ChiCommerce
    networks:
      - ChiNetwork
    ports:
      - "7000:7000"
    env_file:
      - .env


  # redis:
  #   image: redis
  #   container_name: ChiCommerce_redis
  #   networks:
  #     - ChiNetwork
  #   volumes:
  #     - redis_data:/data
  #   ports:
  #     - 127.0.0.1:6379:6379
  #   command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
  #   env_file:
  #     - .env

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    restart: always
    container_name: ChiCommerce_celery
    networks:
      - ChiNetwork
    env_file:
      - .env


networks:
  ChiNetwork:
    driver: bridge


# volumes:
#   redis_data:
