#! /bin/bash

sudo docker image prune -f
# docker volume prune -f
sudo docker ps
sudo docker compose up --build -d
sudo docker image prune -f
# docker volume prune -f
sudo docker ps
# docker-compose exec web flask db init
# docker-compose exec web flask db migrate
# docker-compose exec web flask db upgrade
sudo docker logs -f Chi_Icon
