import os
from dotenv import load_dotenv

load_dotenv()

FRONTEND_VERIFICATION_URL = os.getenv("FRONTEND_VERIFICATION_URL")
SENDER_EMAIL = os.getenv("SENDER_EMAIL")
SENDER_NAME = os.getenv("SENDER_NAME")
FRONTEND_LOGIN_URL = os.getenv("FRONTEND_LOGIN_URL")
ACCESS_TOKEN_EXPIRES = os.getenv("ACCESS_TOKEN_EXPIRES")
REDIS_URL = os.getenv("REDIS_URL")
REDIS_EXPIRE_TIME = os.getenv("REDIS_EXPIRE_TIME")
EXCEPTION_MESSAGE = os.getenv("EXCEPTION_MESSAGE")
