"""Make reset_otp nullable

Revision ID: 151cec567e00
Revises: d384bd6e1278
Create Date: 2025-03-11 18:16:34.910604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151cec567e00'
down_revision = 'd384bd6e1278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('reset_otp',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('otp_expiration',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('otp_expiration',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('reset_otp',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
