"""empty message

Revision ID: 2d1b6c1ebbfd
Revises: 390745ed47cd
Create Date: 2025-07-29 11:05:32.044372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1b6c1ebbfd'
down_revision = '390745ed47cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=50), nullable=True),
    sa.Column('transaction_type', sa.Enum('deposit', 'withdrawal', 'payment', 'refund', name='transactiontype'), nullable=True),
    sa.Column('transaction_status', sa.Enum('success', 'failed', name='transactionstatus'), nullable=True),
    sa.Column('authorization_dict', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index('ix_transaction_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_transaction_user_id', ['user_id'], unique=False)

    op.create_table('product_purchased',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_purchased')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index('ix_transaction_user_id')
        batch_op.drop_index('ix_transaction_created_at')

    op.drop_table('transaction')
    # ### end Alembic commands ###
