"""empty message

Revision ID: 390745ed47cd
Revises: cc0999cbb63e
Create Date: 2025-07-13 01:08:42.790955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390745ed47cd'
down_revision = 'cc0999cbb63e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_ref_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('cart_ref_id')

    # ### end Alembic commands ###
