"""empty message

Revision ID: 421c71a5de75
Revises: b894ba8b17bf
Create Date: 2025-03-13 15:07:14.503674

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "421c71a5de75"
down_revision = "b894ba8b17bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("specification_3", sa.String(length=100), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("specification_3")

    # ### end Alembic commands ###
