"""empty message

Revision ID: 452ff2ddf18f
Revises: 649b4410f909
Create Date: 2025-03-13 12:52:18.602261

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "452ff2ddf18f"
down_revision = "649b4410f909"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("color", sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column("model", sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("model")
        batch_op.drop_column("color")

    # ### end Alembic commands ###
