"""empty message

Revision ID: 649b4410f909
Revises: 
Create Date: 2025-03-13 11:03:31.113323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649b4410f909'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('reset_otp', sa.String(length=10), nullable=True),
    sa.Column('otp_expiration', sa.DateTime(), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('out_of_stock', sa.Boolean(), nullable=True),
    sa.Column('category_id', sa.String(length=50), nullable=False),
    sa.Column('specification_1', sa.String(length=100), nullable=True),
    sa.Column('specification_2', sa.String(length=100), nullable=True),
    sa.Column('specification_4', sa.String(length=100), nullable=True),
    sa.Column('specification_5', sa.String(length=100), nullable=True),
    sa.Column('specification_6', sa.String(length=100), nullable=True),
    sa.Column('specification_7', sa.String(length=100), nullable=True),
    sa.Column('specification_8', sa.String(length=100), nullable=True),
    sa.Column('specification_9', sa.String(length=100), nullable=True),
    sa.Column('specification_10', sa.String(length=100), nullable=True),
    sa.Column('specification_11', sa.String(length=100), nullable=True),
    sa.Column('specification_12', sa.String(length=100), nullable=True),
    sa.Column('specification_13', sa.String(length=100), nullable=True),
    sa.Column('specification_14', sa.String(length=100), nullable=True),
    sa.Column('specification_15', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('category')
    # ### end Alembic commands ###
