"""empty message

Revision ID: ee4383789766
Revises: 273f05f5e4fa
Create Date: 2025-04-15 11:13:21.927211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee4383789766'
down_revision = '273f05f5e4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=500), nullable=False))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
